name: TimeBuddy
options:
  bundleIdPrefix: com.padolabs
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

targets:
  TimeBuddy:
    type: application
    platform: macOS
    sources:
      - path: TimeBuddy
        excludes:
          - Resources
      - path: TimeBuddy/Resources/Assets.xcassets
        buildPhase: resources
    info:
      path: TimeBuddy/Resources/Info.plist
    entitlements:
      path: TimeBuddy/Resources/TimeBuddy.entitlements
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.padolabs.TimeBuddy
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.9"
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        INFOPLIST_FILE: TimeBuddy/Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: TimeBuddy/Resources/TimeBuddy.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
